<a href="https://colab.research.google.com/github/GiangAnhTuan-20146450/Bai-Tap-AI/blob/main/AI_W8_24_03_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron   
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler  
import pandas as pd

In [ ]:
url = 'lung_cancer_examples.csv'
data = pd.read_csv(url)
data.head()

     Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [ ]:
dataFrame=data.drop(['Name','Surname'],axis=1).head()

In [ ]:
dataFrame.head()

   Age  Smokes  AreaQ  Alkhol  Result
0   35       3      5       4       1
1   27      20      2       5       1
2   30       0      5       2       0
3   28       0      8       1       0
4   68       4      5       6       1

In [ ]:
x=dataFrame.iloc[:,:4]
y=dataFrame.iloc[:,4]

In [ ]:
x.head()

   Age  Smokes  AreaQ  Alkhol
0   35       3      5       4
1   27      20      2       5
2   30       0      5       2
3   28       0      8       1
4   68       4      5       6

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [ ]:
Sc = StandardScaler()
Sc.fit(x_train)

StandardScaler()

In [ ]:
x_train_std=Sc.transform(x_train)
x_test_std=Sc.transform(x_test)

In [ ]:
model = Perceptron(max_iter=40,eta0=0.1, random_state=0)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(y_test)
print(y_pred)
print("Do chinh xac khi chua scale: ", accuracy_score(y_test, y_pred))

2    0
1    1
Name: Result, dtype: int64
[1 1]
Do chinh xac khi chua scale:  0.5

In [ ]:
model = Perceptron(max_iter=40,eta0=0.1, random_state=0)
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_test)
print(y_pred)
print('Do chinh xac khi scale: ', accuracy_score(y_test, y_pred))

2    0
1    1
Name: Result, dtype: int64
[0 1]
Do chinh xac khi scale:  1.0

In [ ]:
url = 'pima-indians-diabetes.csv'
data = pd.read_csv(url)
data.head()

   6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [ ]:
x = data.iloc[:,:8]
y = data.iloc[:,8]

In [ ]:
x.head()

   6  148  72  35    0  33.6  0.627  50
0  1   85  66  29    0  26.6  0.351  31
1  8  183  64   0    0  23.3  0.672  32
2  1   89  66  23   94  28.1  0.167  21
3  0  137  40  35  168  43.1  2.288  33
4  5  116  74   0    0  25.6  0.201  30

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [ ]:
Sc = StandardScaler()
Sc.fit(x_train)

StandardScaler()

In [ ]:
x_train_std=Sc.transform(x_train)
x_test_std=Sc.transform(x_test)

In [ ]:
model = Perceptron(max_iter=40,eta0=0.1, random_state=0)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(y_test)
print(y_pred)
print("Do chinh xac khi chua scale: ", accuracy_score(y_test, y_pred))

141    0
369    1
672    0
447    1
277    0
      ..
750    0
167    0
120    0
197    1
655    0
Name: 1, Length: 231, dtype: int64
[0 0 0 0 1 0 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1
 0 0 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 1 0 0 0 1
 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0 1 1 1 0 0 1 0 1 0 1 0 0 1 1 0 1 1 0 0 0 1 0
 1 0 1 0 1 0 0 0 0 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 1
 1 1 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1 1 0 0 1 0 0
 0 0 1 1 0 1 1 0 0]
Do chinh xac khi chua scale:  0.5887445887445888

In [ ]:
model = Perceptron(max_iter=40,eta0=0.1, random_state=0)
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_test)
print(y_pred)
print('Do chinh xac khi scale: ', accuracy_score(y_test, y_pred))

141    0
369    1
672    0
447    1
277    0
      ..
750    0
167    0
120    0
197    1
655    0
Name: 1, Length: 231, dtype: int64
[0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0
 1 0 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0
 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 0 0 1
 0 0 0 0 0 0 1 0 0]
Do chinh xac khi scale:  0.683982683982684